name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Latex Docker image build
      run: docker build . --file Dockerfile --tag lukasmerk/latex:latest
      working-directory: latex
