name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v2
      name: Build the Docker image
      working-directory: latex
      run: docker build . --file Dockerfile --tag lukasmerk/latex:latest
